# Generated by Django 4.2.23 on 2025-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Unnamed Exercise', max_length=100),
            preserve_default=False,
        ),
    ]
